name: penalise
channels:
  - pytorch
  - anaconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - accimage=0.2.0=py38hed9865a_3
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py38h6a678d5_7
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py38h06a4308_0
  - cffi=1.16.0=py38h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=41.0.3=py38hdda0065_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.4=py38h06a4308_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - intel-ipp=2019.1.144=h711154d_3
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipython=8.12.2=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libjpeg-turbo=2.1.1=h7f98852_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hf1b16e4_1
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib=3.7.2=py38h06a4308_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.6=py38h417a72b_1
  - mkl_random=1.2.2=py38h417a72b_1
  - munch=2.5.0=pyhd3eb1b0_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.14=h5eee18b_0
  - packaging=24.1=py38h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py38ha6cbd5a_0
  - pip=23.1.2=py38h06a4308_0
  - ply=3.11=py38_0
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - pyopenssl=23.2.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.10=py38h6a678d5_0
  - pyqt5-sip=12.13.0=py38h5eee18b_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h955ad1f_4
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python_abi=3.8=2_cp38
  - pytorch=1.12.0=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_0
  - setuptools=67.8.0=py38h06a4308_0
  - sip=6.7.12=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38h06a4308_0
  - torchaudio=0.12.0=py38_cu113
  - traitlets=5.7.1=py38h06a4308_0
  - typing_extensions=4.6.3=py38h06a4308_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - urllib3=1.26.18=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==1.4.0
    - appdirs==1.4.4
    - cached-property==1.5.2
    - chex==0.1.7
    - clarabel==0.6.0
    - click==8.1.3
    - cplex==22.1.0.0
    - cvxpy==1.4.1
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - ecos==2.0.12
    - etils==1.3.0
    - flax==0.7.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.0
    - jax==0.4.13
    - jaxlib==0.4.13
    - joblib==1.3.1
    - jsonpatch==1.33
    - jsonpointer==2.4
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - ml-dtypes==0.2.0
    - msgpack==1.0.5
    - nest-asyncio==1.5.6
    - networkx==3.1
    - opt-einsum==3.3.0
    - optax==0.1.5
    - orbax-checkpoint==0.2.3
    - osqp==0.6.3
    - pathtools==0.1.2
    - pipreqs==0.4.13
    - prefetch-generator==1.0.3
    - protobuf==4.23.3
    - psutil==5.9.5
    - ptflops==0.7
    - pybind11==2.11.1
    - pytorch-influence-functions==0.1.1
    - pyyaml==6.0
    - qdldl==0.1.7.post0
    - rich==13.4.2
    - scikit-learn==1.3.0
    - scipy==1.7.3
    - scs==3.2.3
    - sentry-sdk==1.26.0
    - setproctitle==1.3.2
    - smmap==5.0.0
    - tensorstore==0.1.40
    - threadpoolctl==3.2.0
    - toolz==0.12.0
    - torchnet==0.0.4
    - tornado==6.3.2
    - tqdm==4.65.0
    - visdom==0.2.4
    - wandb==0.15.4
    - websocket-client==1.6.1
    - yarg==0.1.9
    - zipp==3.16.2
prefix: /home/bupt_fuxl/.conda/envs/penalise
